version: "2"
services:
  chirpstack-network-server:
    build:
      context: .
      dockerfile: Dockerfile-devel
    command: make serve
    volumes:
      - ./:/chirpstack-network-server
    links:
      - postgres
      - redis
      - mosquitto
      - rabbitmq
    environment:
      - DB_AUTOMIGRATE=true
      - NET_ID=010203
      - BAND=EU868
      - REDIS_URL=redis://redis:6379
      - GW_MQTT_SERVER=tcp://mosquitto:1883
      - GW_SERVER_JWT_SECRET=verysecret
      - POSTGRES_DSN=postgres://chirpstack_ns:chirpstack_ns@postgres/chirpstack_ns?sslmode=disable
      - TEST_POSTGRES_DSN=postgres://chirpstack_ns:chirpstack_ns@postgres/chirpstack_ns?sslmode=disable
      - TEST_REDIS_SERVERS=redis:6379
      - TEST_MQTT_SERVER=tcp://mosquitto:1883
      - TEST_RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/

  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=chirpstack_ns
      - POSTGRES_USER=chirpstack_ns
      - POSTGRES_DB=chirpstack_ns

  redis:
    image: redis:3.0.7-alpine

  mosquitto:
    image: eclipse-mosquitto:1.6

  rabbitmq:
    image: rabbitmq:3-alpine
