# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

[[constraint]]
  branch = "master"
  name = "github.com/brocaar/lorawan"

[[constraint]]
  version = "v1.1.1"
  name = "github.com/eclipse/paho.mqtt.golang"

# override is needed because of grpc-middleware having constraint on master branch
[[override]]
  version = "v1.1.0"
  name = "github.com/golang/protobuf"

[[constraint]]
  branch = "master"
  name = "github.com/jmoiron/sqlx"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/rubenv/sql-migrate"

[[constraint]]
  version = "3.0.0"
  name = "github.com/gofrs/uuid"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.6"

[[constraint]]
  name = "github.com/smartystreets/goconvey"
  version = "1.6.3"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.14.0"

[[constraint]]
  version = "v1.0.0"
  name = "github.com/grpc-ecosystem/go-grpc-middleware"

[[constraint]]
  version = "0.0.3"
  name = "github.com/spf13/cobra"

[[constraint]]
  version = "v1.1.0"
  name = "github.com/spf13/viper"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/NickBall/go-aes-key-wrap"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "v1.2.2"

[[constraint]]
  name = "github.com/gomodule/redigo"
  version = "2.0.0"
