baseURL = "https://www.chirpstack.io/network-server/"
languageCode = "en-us"
title = "ChirpStack Network Server documentation"
googleAnalytics = "UA-3512995-9"
pygmentsUseClasses = true
theme = "chirpstack-hugo-theme"

[[menu.main]]
    pre = "<i class='fas fa-hand-point-right'></i>"
    name = "Overview"
    identifier = "overview"
    url = "/overview/"
    weight = 1

[[menu.main]]
    pre = "<i class='fas fa-download'></i>"
    name = "Install"
    identifier = "install"
    url = "/install/"
    weight = 2

[[menu.main]]
    pre = "<i class='fas fa-cogs'></i>"
    name = "Features"
    identifier = "features"
    url = "/features/"
    weight = 3

[[menu.main]]
    pre = "<i class='fas fa-code'></i>"
    name = "Integrate"
    identifier = "integrate"
    url = "/integrate/"
    weight = 4

[[menu.main]]
    pre = "<i class='fas fa-chart-line'></i>"
    name = "Metrics"
    identifier = "metrics"
    url = "/metrics/"
    weight = 5

[[menu.main]]
    pre = "<i class='fab fa-github'></i>"
    name = "Community & support"
    identifier = "community"
    url = "/community/"
    weight = 6

[params]
version = "3.5.0"
component = "chirpstack-network-server"
