baseURL = "https://www.loraserver.io/loraserver/"
languageCode = "en-us"
title = "LoRa Server Server documentation"
googleAnalytics = "UA-3512995-9"
pygmentsUseClasses = true

[[menu.main]]
    pre = "<i class='fas fa-hand-point-right'></i>"
    name = "Overview"
    identifier = "overview"
    url = "/overview/"
    weight = 1

[[menu.main]]
    pre = "<i class='fas fa-download'></i>"
    name = "Install"
    identifier = "install"
    url = "/install/"
    weight = 2

[[menu.main]]
    pre = "<i class='fas fa-cogs'></i>"
    name = "Features"
    identifier = "features"
    url = "/features/"
    weight = 3

[[menu.main]]
    pre = "<i class='fas fa-code'></i>"
    name = "Integrate"
    identifier = "integrate"
    url = "/integrate/"
    weight = 4

[[menu.main]]
    pre = "<i class='fab fa-github'></i>"
    name = "Community & support"
    identifier = "community"
    url = "/community/"
    weight = 5

[params]
version = "3.0.0"
